# Generated by Django 3.2 on 2021-04-22 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
